apiVersion: v1
kind: Service
metadata:
  name: watti-watchman
  labels:
    app: watti-watchman
spec:
  selector:
    app.kubernetes.io/name: watti-watchman
  ports:
    - name: web
      port: 9292
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: watti-watchman
  labels:
    default-prometheus.lks.klaut.io/skip: "on"
    longterm-prometheus.lks.klaut.io/keep: "on"
spec:
  selector:
    matchLabels:
      app: watti-watchman
  endpoints:
  - port: web
    interval: 200ms
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: watti-watchman
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: watti-watchman
  template:
    metadata:
      labels:
        app: watti-watchman
        app.kubernetes.io/name: watti-watchman
    spec:
      containers:
      - image: ghcr.io/tonobo/watti_watchman:main
        imagePullPolicy: Always
        name: watti-watchman
        volumeMounts:
          - name: config
            mountPath: /app/watti_watchman.yml
            subPath: watti_watchman.yml
      restartPolicy: Always
      volumes:
        - name: config
          secret:
            secretName: watti-config
