$schema: http://json-schema.org/draft-07/schema#
$id: http://watti.klaut.local/schemas/hass_dynamic_config_service_schema.yml
title: Hass Dynamic Config
type: object
required:
  - mqtt_connection_name
properties:
  type:
    type: string
    const: HassDynamicConfig
  kind:
    type: string
    const: Service
  mqtt_connection_name:
    type: string
    description: Name of an existing MQTT connection from mqtt_connections array.
  persistent:
    type: boolean 
    description: If true, dynmic configuration will be kept in mqtt and will survive watti_watchman restarts.
    default: false
additionalProperties: false
